# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_frontend_cart_edit:
    path: /edit-item/{id}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.cart_item:editAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:editItem.html.twig
